import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const year = new Date().getFullYear();

const lato = Lato({
  weight: ["400", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: `Liga de Fútbol Distrital de Monsefú - ${year}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${lato.className}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
